import { Injectable } from '@angular/core';

@Injectable()
export class ObrasService {
    obras: Obra[];

    constructor(){
        this.obras = [
            {
              id : "5c1c2be74be5a91a30e25d72",
              clave_municipal : "AP-DUOP-10/18",
              nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD MURO FIRME",
              localidad : "LA CAMPANA",
              meta : "1 OBRA",
              beneficiarios_directos : 500,
              direccion_responsable : "DESARROLLO SOCIAL",
              numero_contrato : "DA-DES-01/01",
              fecha_contrato : "2018-12-19T00:00:00.000Z",
              supervisor : "Zutano",
              tipo_ejecucion : "CONTRATO",
              programa : "FONDO III",
              inversion_aprobada : 234789.5,
              contratista : "ING. MELGOZA",
              estado : "TERMINADA",
            },

            {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "REHABILITACION DE LA CALLE FULANA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              },

              {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD CASA NUEVA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              },

              {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD CASA NUEVA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              },
              {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD CASA NUEVA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              },

              {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD CASA NUEVA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              },
              {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD CASA NUEVA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              },
              {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD CASA NUEVA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              },
              {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD CASA NUEVA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              },
              {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD CASA NUEVA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              },
              {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD CASA NUEVA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              },
              {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD CASA NUEVA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              },
              {
                id : "5c1c2be74be5a91a30e25d72",
                clave_municipal : "AP-DUOP-10/18",
                nombre_obra : "PROGRAMA DE MEJORA TU VIVIENDA EN SU MODALIDAD CASA NUEVA",
                localidad : "LA CAMPANA",
                meta : "1 OBRA",
                beneficiarios_directos : 500,
                direccion_responsable : "DESARROLLO SOCIAL",
                numero_contrato : "DA-DES-01/01",
                fecha_contrato : "2018-12-19T00:00:00.000Z",
                supervisor : "Zutano",
                tipo_ejecucion : "CONTRATO",
                programa : "FONDO III",
                inversion_aprobada : 234789.5,
                contratista : "ING. MELGOZA",
                estado : "TERMINADA",
              }
          ];
      
    }
  
  getObras():Obra[] {
    return this.obras;
  }

  getObra(id: string){
    return this.obras[id];
  }

}

export interface Obra{
    id : String,
    clave_municipal : String,
    nombre_obra : String,
    localidad : String,
    meta :  String,
    beneficiarios_directos: number,
    direccion_responsable : String,
    numero_contrato : String,
    fecha_contrato : String,
    supervisor : String,
    tipo_ejecucion : String,
    programa : String,
    inversion_aprobada : number,
    contratista : String,
    estado :  String
}